package model;
// Generated May 25, 2015 11:24:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;
     private String username;
     private String password;
     private String image;
     private int type;
     private int status;
     private String email;
     private Date birthday;
     private String nationality;
     private Integer sex;
     private String occupation;
     private Date createdDate;
     private Date modifiedDate;
     private Integer jobStartTime;
     private Integer jobEndTime;
     private Set comments = new HashSet(0);
     private Set offers = new HashSet(0);
     private Set messagesForAccountId1 = new HashSet(0);
     private Set events = new HashSet(0);
     private Set messagesForAccountId2 = new HashSet(0);

    public Account() {
    }

	
    public Account(int id, String firstName, String lastName, String username, String password, int type, int status, String email, Date createdDate) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.username = username;
        this.password = password;
        this.type = type;
        this.status = status;
        this.email = email;
        this.createdDate = createdDate;
    }
    public Account(int id, String firstName, String lastName, String username, String password, String image, int type, int status, String email, Date birthday, String nationality, Integer sex, String occupation, Date createdDate, Date modifiedDate, Integer jobStartTime, Integer jobEndTime, Set comments, Set offers, Set messagesForAccountId1, Set events, Set messagesForAccountId2) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
       this.username = username;
       this.password = password;
       this.image = image;
       this.type = type;
       this.status = status;
       this.email = email;
       this.birthday = birthday;
       this.nationality = nationality;
       this.sex = sex;
       this.occupation = occupation;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.jobStartTime = jobStartTime;
       this.jobEndTime = jobEndTime;
       this.comments = comments;
       this.offers = offers;
       this.messagesForAccountId1 = messagesForAccountId1;
       this.events = events;
       this.messagesForAccountId2 = messagesForAccountId2;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Integer getJobStartTime() {
        return this.jobStartTime;
    }
    
    public void setJobStartTime(Integer jobStartTime) {
        this.jobStartTime = jobStartTime;
    }
    public Integer getJobEndTime() {
        return this.jobEndTime;
    }
    
    public void setJobEndTime(Integer jobEndTime) {
        this.jobEndTime = jobEndTime;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getOffers() {
        return this.offers;
    }
    
    public void setOffers(Set offers) {
        this.offers = offers;
    }
    public Set getMessagesForAccountId1() {
        return this.messagesForAccountId1;
    }
    
    public void setMessagesForAccountId1(Set messagesForAccountId1) {
        this.messagesForAccountId1 = messagesForAccountId1;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }
    public Set getMessagesForAccountId2() {
        return this.messagesForAccountId2;
    }
    
    public void setMessagesForAccountId2(Set messagesForAccountId2) {
        this.messagesForAccountId2 = messagesForAccountId2;
    }




}


