package model;
// Generated May 25, 2015 11:24:21 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private CommentId id;
     private Account account;
     private Event event;
     private String content;
     private Date createdDate;

    public Comment() {
    }

    public Comment(CommentId id, Account account, Event event, String content, Date createdDate) {
       this.id = id;
       this.account = account;
       this.event = event;
       this.content = content;
       this.createdDate = createdDate;
    }
   
    public CommentId getId() {
        return this.id;
    }
    
    public void setId(CommentId id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Event getEvent() {
        return this.event;
    }
    
    public void setEvent(Event event) {
        this.event = event;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


