package model;
// Generated May 25, 2015 11:24:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private int id;
     private Account account;
     private String content;
     private int mode;
     private int status;
     private Date startDate;
     private Date endDate;
     private Date createdDate;
     private String modifier;
     private Date modifiedDate;
     private Set comments = new HashSet(0);

    public Event() {
    }

	
    public Event(int id, Account account, String content, int mode, int status, Date startDate, Date endDate, Date createdDate) {
        this.id = id;
        this.account = account;
        this.content = content;
        this.mode = mode;
        this.status = status;
        this.startDate = startDate;
        this.endDate = endDate;
        this.createdDate = createdDate;
    }
    public Event(int id, Account account, String content, int mode, int status, Date startDate, Date endDate, Date createdDate, String modifier, Date modifiedDate, Set comments) {
       this.id = id;
       this.account = account;
       this.content = content;
       this.mode = mode;
       this.status = status;
       this.startDate = startDate;
       this.endDate = endDate;
       this.createdDate = createdDate;
       this.modifier = modifier;
       this.modifiedDate = modifiedDate;
       this.comments = comments;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public int getMode() {
        return this.mode;
    }
    
    public void setMode(int mode) {
        this.mode = mode;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }




}


