package com.model;
// Generated Jun 8, 2015 4:53:33 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Offer generated by hbm2java
 */
public class Offer  implements java.io.Serializable {


     private int idOffer;
     private Account account;
     private String title;
     private String content;
     private int mode;
     private Date createdDate;
     private String modifier;
     private Date modifiedDate;

    public Offer() {
    }

	
    public Offer(int idOffer, Account account, String title, String content, int mode, Date createdDate) {
        this.idOffer = idOffer;
        this.account = account;
        this.title = title;
        this.content = content;
        this.mode = mode;
        this.createdDate = createdDate;
    }
    public Offer(int idOffer, Account account, String title, String content, int mode, Date createdDate, String modifier, Date modifiedDate) {
       this.idOffer = idOffer;
       this.account = account;
       this.title = title;
       this.content = content;
       this.mode = mode;
       this.createdDate = createdDate;
       this.modifier = modifier;
       this.modifiedDate = modifiedDate;
    }
   
    public int getIdOffer() {
        return this.idOffer;
    }
    
    public void setIdOffer(int idOffer) {
        this.idOffer = idOffer;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public int getMode() {
        return this.mode;
    }
    
    public void setMode(int mode) {
        this.mode = mode;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifier() {
        return this.modifier;
    }
    
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


